// Sanitized display-only migration defaults. No accounts, hashes, or source files.
export const initialSettings={
  "displaySections": [
    {
      "id": 1,
      "section_key": "identification",
      "label": "Identification",
      "sort_order": 10,
      "is_visible": 1
    },
    {
      "id": 2,
      "section_key": "keyed",
      "label": "Keyed Stem",
      "sort_order": 20,
      "is_visible": 1
    },
    {
      "id": 3,
      "section_key": "flat",
      "label": "Flat Stem",
      "sort_order": 30,
      "is_visible": 1
    },
    {
      "id": 4,
      "section_key": "manufacturing",
      "label": "Configurator & Drawing Summary",
      "sort_order": 40,
      "is_visible": 1
    }
  ],
  "displayFields": [
    {
      "id": 1,
      "field_key": "valve.valve_id",
      "section_key": "identification",
      "label": "Valve ID",
      "sort_order": 10,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 2,
      "field_key": "valve.valve_brand",
      "section_key": "identification",
      "label": "Brand",
      "sort_order": 20,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 3,
      "field_key": "valve.valve_size",
      "section_key": "identification",
      "label": "Size",
      "sort_order": 30,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 4,
      "field_key": "valve.valve_class",
      "section_key": "identification",
      "label": "Class",
      "sort_order": 40,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 5,
      "field_key": "valve.valve_model_number",
      "section_key": "identification",
      "label": "Model Number",
      "sort_order": 50,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 6,
      "field_key": "valve.valve_port",
      "section_key": "identification",
      "label": "Port",
      "sort_order": 60,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 7,
      "field_key": "valve.stem_type",
      "section_key": "identification",
      "label": "Stem Type",
      "sort_order": 70,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 8,
      "field_key": "valve.description",
      "section_key": "identification",
      "label": "Description",
      "sort_order": 80,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 9,
      "field_key": "keyed.stem_diameter",
      "section_key": "keyed",
      "label": "Stem Diameter",
      "sort_order": 10,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 10,
      "field_key": "keyed.stem_height",
      "section_key": "keyed",
      "label": "Stem Height",
      "sort_order": 20,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 11,
      "field_key": "keyed.key_qty",
      "section_key": "keyed",
      "label": "Key Quantity",
      "sort_order": 30,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": "Keys",
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 12,
      "field_key": "keyed.key_width",
      "section_key": "keyed",
      "label": "Key Width",
      "sort_order": 40,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": "MM",
      "decimal_places": 2,
      "help_text": null
    },
    {
      "id": 13,
      "field_key": "keyed.key_cross",
      "section_key": "keyed",
      "label": "Key Cross",
      "sort_order": 50,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 14,
      "field_key": "keyed.valve_bhc",
      "section_key": "keyed",
      "label": "Valve Bolt-hole Circle",
      "sort_order": 60,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": 2,
      "help_text": null
    },
    {
      "id": 15,
      "field_key": "keyed.valve_hole_dia",
      "section_key": "keyed",
      "label": "Valve Hole Diameter",
      "sort_order": 70,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 16,
      "field_key": "keyed.valve_hole_qty",
      "section_key": "keyed",
      "label": "Valve Hole Quantity",
      "sort_order": 80,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 17,
      "field_key": "keyed.valve_start_angle",
      "section_key": "keyed",
      "label": "Valve Hole Start Angle",
      "sort_order": 90,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": "Degrees ",
      "decimal_places": 2,
      "help_text": null
    },
    {
      "id": 18,
      "field_key": "flat.stem_height",
      "section_key": "flat",
      "label": "Stem Height",
      "sort_order": 10,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 19,
      "field_key": "flat.flat_width",
      "section_key": "flat",
      "label": "Flat Width",
      "sort_order": 20,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 20,
      "field_key": "flat.flat_depth",
      "section_key": "flat",
      "label": "Flat Depth",
      "sort_order": 30,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 21,
      "field_key": "flat.valve_bhc",
      "section_key": "flat",
      "label": "Valve Bolt-hole Circle",
      "sort_order": 40,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 22,
      "field_key": "flat.valve_hole_dia",
      "section_key": "flat",
      "label": "Valve Hole Diameter",
      "sort_order": 50,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 23,
      "field_key": "flat.valve_hole_qty",
      "section_key": "flat",
      "label": "Valve Hole Quantity",
      "sort_order": 60,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 24,
      "field_key": "flat.valve_start_angle",
      "section_key": "flat",
      "label": "Valve Hole Start Angle",
      "sort_order": 70,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": "Degrees ",
      "decimal_places": 2,
      "help_text": null
    },
    {
      "id": 25,
      "field_key": "flat.packing_flange",
      "section_key": "flat",
      "label": "Packing Flange",
      "sort_order": 80,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 26,
      "field_key": "flat.packing_flange_width",
      "section_key": "flat",
      "label": "Packing-flange Width",
      "sort_order": 90,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 27,
      "field_key": "flat.packing_flange_length",
      "section_key": "flat",
      "label": "Packing-flange Length",
      "sort_order": 100,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 28,
      "field_key": "flat.packing_flange_angle",
      "section_key": "flat",
      "label": "Packing-flange Angle",
      "sort_order": 110,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 29,
      "field_key": "flat.dia_reduction",
      "section_key": "flat",
      "label": "Diameter Reduction",
      "sort_order": 120,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 30,
      "field_key": "flat.dia_reduction_value",
      "section_key": "flat",
      "label": "Diameter-reduction Value",
      "sort_order": 130,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 31,
      "field_key": "flat.stem_thread",
      "section_key": "flat",
      "label": "Stem Thread",
      "sort_order": 140,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 32,
      "field_key": "flat.stem_thread_dia",
      "section_key": "flat",
      "label": "Stem-thread Diameter",
      "sort_order": 150,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 33,
      "field_key": "flat.stem_thread_depth",
      "section_key": "flat",
      "label": "Stem-thread Depth",
      "sort_order": 160,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 34,
      "field_key": "flat.u_bolt",
      "section_key": "flat",
      "label": "U-bolt",
      "sort_order": 170,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 35,
      "field_key": "flat.u_bolt_valve_width",
      "section_key": "flat",
      "label": "U-bolt Valve Width",
      "sort_order": 180,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 36,
      "field_key": "flat.u_bolt_valve_length",
      "section_key": "flat",
      "label": "U-bolt Valve Length",
      "sort_order": 190,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 37,
      "field_key": "flat.valve_pattern_type",
      "section_key": "flat",
      "label": "Valve Pattern Type",
      "sort_order": 200,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 38,
      "field_key": "flat.valve_grid_x_distance",
      "section_key": "flat",
      "label": "Grid X Distance",
      "sort_order": 210,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 39,
      "field_key": "flat.valve_grid_y_distance",
      "section_key": "flat",
      "label": "Grid Y Distance",
      "sort_order": 220,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 40,
      "field_key": "summary.last_drawing_created",
      "section_key": "manufacturing",
      "label": "Last Drawing Created",
      "sort_order": 10,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 41,
      "field_key": "summary.last_job",
      "section_key": "manufacturing",
      "label": "Last Job",
      "sort_order": 20,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 42,
      "field_key": "summary.last_quantity",
      "section_key": "manufacturing",
      "label": "Last Quantity",
      "sort_order": 30,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 43,
      "field_key": "summary.configuration",
      "section_key": "manufacturing",
      "label": "Configuration",
      "sort_order": 40,
      "is_visible": 0,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 44,
      "field_key": "summary.fusion_document",
      "section_key": "manufacturing",
      "label": "Fusion Document",
      "sort_order": 50,
      "is_visible": 0,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 45,
      "field_key": "summary.actuator",
      "section_key": "manufacturing",
      "label": "Actuator",
      "sort_order": 60,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    },
    {
      "id": 46,
      "field_key": "summary.total_runs",
      "section_key": "manufacturing",
      "label": "Configurator Runs",
      "sort_order": 70,
      "is_visible": 1,
      "is_highlighted": 0,
      "unit": null,
      "decimal_places": null,
      "help_text": null
    }
  ],
  "referenceDisplays": {
    "actuators": [
      {
        "field_key": "actuator_id",
        "label": "Actuator ID",
        "sort_order": 10,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "actuator_name",
        "label": "Actuator Name",
        "sort_order": 20,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "theme_name",
        "label": "Theme Name",
        "sort_order": 30,
        "is_visible": 0,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "square_size",
        "label": "Square Size",
        "sort_order": 40,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "square_height",
        "label": "Square Height",
        "sort_order": 50,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "sq_rad",
        "label": "SQ Rad",
        "sort_order": 60,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "d_stem",
        "label": "D Stem",
        "sort_order": 70,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "actuator_hole_dia",
        "label": "Actuator Hole Dia",
        "sort_order": 80,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "actuator_bhc",
        "label": "Actuator BHC",
        "sort_order": 90,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "actuator_hole_qty",
        "label": "Actuator Hole Qty",
        "sort_order": 100,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "actuator_start_angle",
        "label": "Actuator Hole Start Angle",
        "sort_order": 110,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "bracket_height",
        "label": "Bracket Height",
        "sort_order": 120,
        "is_visible": 0,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      }
    ],
    "brackets": [
      {
        "field_key": "bracket_id",
        "label": "Bracket ID",
        "sort_order": 10,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "bracket_code",
        "label": "Bracket Code",
        "sort_order": 20,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "actuator_1_bhc",
        "label": "Actuator 1 BHC",
        "sort_order": 30,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "actuator_1_hole_dia",
        "label": "Actuator 1 Hole Dia",
        "sort_order": 40,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "actuator_1_hole_qty",
        "label": "Actuator 1 Hole Qty",
        "sort_order": 50,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "actuator_1_start_angle",
        "label": "Actuator 1 Start Angle",
        "sort_order": 60,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "actuator_2_bhc",
        "label": "Actuator 2 BHC",
        "sort_order": 70,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "actuator_2_hole_dia",
        "label": "Actuator 2 Hole Dia",
        "sort_order": 80,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "actuator_2_hole_qty",
        "label": "Actuator 2 Hole Qty",
        "sort_order": 90,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "actuator_2_start_angle",
        "label": "Actuator 2 Start Angle",
        "sort_order": 100,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "actuator_3_bhc",
        "label": "Actuator 3 BHC",
        "sort_order": 110,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "actuator_3_hole_dia",
        "label": "Actuator 3 Hole Dia",
        "sort_order": 120,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "actuator_3_hole_qty",
        "label": "Actuator 3 Hole Qty",
        "sort_order": 130,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "actuator_3_start_angle",
        "label": "Actuator 3 Start Angle",
        "sort_order": 140,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "valve_bhc",
        "label": "Valve BHC",
        "sort_order": 150,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "valve_hole_dia",
        "label": "Valve Hole Dia",
        "sort_order": 160,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "valve_hole_qty",
        "label": "Valve Hole Qty",
        "sort_order": 170,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "valve_start_angle",
        "label": "Valve Start Angle",
        "sort_order": 180,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "valve_2_bhc",
        "label": "Valve 2 BHC",
        "sort_order": 190,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "valve_2_hole_dia",
        "label": "Valve 2 Hole Dia",
        "sort_order": 200,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "valve_2_hole_qty",
        "label": "Valve 2 Hole Qty",
        "sort_order": 210,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "valve_2_start_angle",
        "label": "Valve 2 Start Angle",
        "sort_order": 220,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "valve_3_bhc",
        "label": "Valve 3 BHC",
        "sort_order": 230,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "valve_3_hole_dia",
        "label": "Valve 3 Hole Dia",
        "sort_order": 240,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "valve_3_hole_qty",
        "label": "Valve 3 Hole Qty",
        "sort_order": 250,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "valve_3_start_angle",
        "label": "Valve 3 Start Angle",
        "sort_order": 260,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "bracket_width",
        "label": "Bracket Width",
        "sort_order": 270,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "bracket_length",
        "label": "Bracket Length",
        "sort_order": 280,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "bracket_height",
        "label": "Bracket Height",
        "sort_order": 290,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "actuator_bracket_center_hole",
        "label": "Actuator Bracket Center Hole",
        "sort_order": 300,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "valve_bracket_center_hole",
        "label": "Valve Bracket Center Hole",
        "sort_order": 310,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "packing_flange",
        "label": "Packing Flange",
        "sort_order": 320,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "packing_flange_width",
        "label": "Packing Flange Width",
        "sort_order": 330,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "packing_flange_length",
        "label": "Packing Flange Length",
        "sort_order": 340,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "packing_flange_angle",
        "label": "Packing Flange Angle",
        "sort_order": 350,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "d_actuator_bracket_center_hole_offset",
        "label": "D Actuator Bracket Center Hole Offset",
        "sort_order": 360,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "d_actuator_bhc_offset",
        "label": "D Actuator BHC Offset",
        "sort_order": 370,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "hole_grid_length",
        "label": "Hole Grid Length",
        "sort_order": 380,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      },
      {
        "field_key": "hole_grid_width",
        "label": "Hole Grid Width",
        "sort_order": 390,
        "is_visible": 1,
        "is_highlighted": 0,
        "unit": null,
        "decimal_places": null,
        "help_text": null
      }
    ]
  },
  "configuratorSettings": {
    "mountingTolerance": 0.06,
    "packingGridTolerance": 0.08,
    "angleTolerance": 0.51,
    "squareTolerance": 0.01
  }
};
